name: build pipeline

on:
    push:
        branches:
            - main
    pull_request:

jobs:
    build:
        name: external workflow
        uses: tehw0lf/workflows/.github/workflows/build-test-publish.yml@main
        permissions:
            actions: write
            attestations: write
            contents: write
            packages: write
            id-token: write
            security-events: write
            pull-requests: write
        with:
            tool: "npm"
            lint: "run lint"
            test: "run test"
            e2e: "run e2e"
            build_branch: "run build"
            build_main: "run build --skip-nx-cache"
            artifact_path: "dist"
            docker_meta: '[{"name":"yaft-admin","file":"Dockerfile"}]'
            npm_audit_omit_dev: true
        cyclonedx_ignore_npm_errors: true
        secrets:
            NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}
