name: weekly image scan

on:
  schedule:
    - cron: "0 8 * * 1"
  workflow_dispatch:

jobs:
  scan:
    name: external workflow
    uses: tehw0lf/workflows/.github/workflows/post-publish-verification.yml@main
    permissions:
      contents: read
      packages: read
      security-events: write
      pull-requests: write
    with:
      docker_meta: '[{"name":"yaft-admin","file":"Dockerfile"}]'
